// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_rdWrZT7cWowLoZ-8YBovuF6L2pjA4To',
    appId: '1:874118977885:web:0a4ff25a40356d0bfcb0b4',
    messagingSenderId: '874118977885',
    projectId: 'wegram-23ec9',
    authDomain: 'wegram-23ec9.firebaseapp.com',
    storageBucket: 'wegram-23ec9.appspot.com',
    measurementId: 'G-2MNNMY2QKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCoZzMQ8A9WcDase5IRgKz1BvE7EZRkLg',
    appId: '1:874118977885:android:63c65c1223830aa1fcb0b4',
    messagingSenderId: '874118977885',
    projectId: 'wegram-23ec9',
    storageBucket: 'wegram-23ec9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxySjZSIA4P6T5oUFcPwZeqPDLr_qI80c',
    appId: '1:874118977885:ios:e1fbd1a00155c88bfcb0b4',
    messagingSenderId: '874118977885',
    projectId: 'wegram-23ec9',
    storageBucket: 'wegram-23ec9.appspot.com',
    iosClientId: '874118977885-7sn9s0f4u75jivvfnkpj3f24157msm6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxySjZSIA4P6T5oUFcPwZeqPDLr_qI80c',
    appId: '1:874118977885:ios:e1fbd1a00155c88bfcb0b4',
    messagingSenderId: '874118977885',
    projectId: 'wegram-23ec9',
    storageBucket: 'wegram-23ec9.appspot.com',
    iosClientId: '874118977885-7sn9s0f4u75jivvfnkpj3f24157msm6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );
}
